name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run docs:build
        
      - name: Debug - Check build output
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Listing files ==="
          ls -la
          echo "=== Checking docs directory ==="
          ls -la docs/ || echo "No docs directory"
          echo "=== Checking build output ==="
          find . -name "dist" -type d 2>/dev/null || echo "No dist directory found"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist/
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
